# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(max_length=4000, verbose_name='texto'),
        ),
    ]
