# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='login',
        ),
    ]
