# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_auto_20161115_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Noticia',
        ),
    ]
