# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_auto_20161115_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
