# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
