# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0007_volposlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volposlogin',
        ),
    ]
