# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0013_volposlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4000, verbose_name='convite')),
                ('image', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sugeridos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.CharField(max_length=100)),
                ('trabalho', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4000, verbose_name='convite')),
                ('image', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Volposlogin',
            new_name='Andamento',
        ),
        migrations.RenameField(
            model_name='andamento',
            old_name='convite',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='andamento',
            old_name='organizacao',
            new_name='subtitulo',
        ),
    ]
