# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0014_auto_20161116_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andamento',
            old_name='subtitulo',
            new_name='organizacao',
        ),
        migrations.RenameField(
            model_name='realizados',
            old_name='subtitulo',
            new_name='organizacao',
        ),
    ]
