# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0015_auto_20161116_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.TextField(max_length=4000, verbose_name='convite')),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
