# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0016_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizados',
            name='comentario',
            field=models.IntegerField(default=0),
        ),
    ]
