# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volposlogin', '0017_realizados_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizados',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='realizados',
            field=models.IntegerField(default=0),
        ),
    ]
