# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgposlogin', '0004_delete_orgposlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgposlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(default='', max_length=400)),
                ('texto', models.TextField(max_length=4000, verbose_name='texto')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('dataNoticia', models.DateTimeField(verbose_name='data da noticia')),
            ],
        ),
    ]
