# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgposlogin', '0006_delete_orgposlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgposlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.CharField(max_length=100)),
                ('trabalho', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=400)),
                ('convite', models.TextField(max_length=4000, verbose_name='convite')),
            ],
        ),
    ]
