# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgposlogin', '0010_auto_20161116_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitacao',
        ),
    ]
