# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgposlogin', '0015_auto_20161126_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4000, verbose_name='descricao')),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Realizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=4000, verbose_name='descricao')),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
