# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='gender',
            new_name='sexo',
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='vagas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
