# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
