# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0002_auto_20161223_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='user_fk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='user_fk',
            field=models.IntegerField(default=0),
        ),
    ]
