# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0003_auto_20161202_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
