# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0003_auto_20161224_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(default=2),
        ),
    ]
