# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0004_auto_20161203_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trabalho',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
