# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0005_auto_20161203_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dia',
            new_name='Dias',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='dias',
            field=models.ManyToManyField(to='unbsolidaria.Dias'),
        ),
    ]
