# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-24 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0006_auto_20161224_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='organizacao_fk',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='voluntario_fk',
            field=models.IntegerField(default=-1),
        ),
    ]
