# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0007_auto_20161203_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='dias',
        ),
    ]
