# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unbsolidaria', '0008_remove_trabalho_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='dias',
            field=models.ManyToManyField(to='unbsolidaria.Dia'),
        ),
    ]
